<?php

namespace Container0uIprZH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFailedControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\FailedController' shared autowired service.
     *
     * @return \App\Controller\FailedController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/FailedController.php';

        $container->services['App\\Controller\\FailedController'] = $instance = new \App\Controller\FailedController();

        $instance->setContainer(($container->privates['.service_locator.ULEwkxg'] ?? $container->load('get_ServiceLocator_ULEwkxgService'))->withContext('App\\Controller\\FailedController', $container));

        return $instance;
    }
}
